global:
  scrape_interval: 15s  # Set the default scrape interval to 15 seconds

scrape_configs:
  - job_name: 'csvserver'
    static_configs:
      - targets: ['csvserver:9300']  # The application target
